// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7NvfZya9wTLpJIE4jU0zwputXoiWxSrI',
    appId: '1:215908689362:web:253caadf44539b011e540b',
    messagingSenderId: '215908689362',
    projectId: 'flow-db99c',
    authDomain: 'flow-db99c.firebaseapp.com',
    storageBucket: 'flow-db99c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE8J6M9fwEwDE0cIAaIa2LpIcjfGlKL2c',
    appId: '1:215908689362:android:464201b1dc4159841e540b',
    messagingSenderId: '215908689362',
    projectId: 'flow-db99c',
    storageBucket: 'flow-db99c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1N16NkC3SEp3v8MqSh6XW2jr6w2J7jms',
    appId: '1:215908689362:ios:074f7df784379ec21e540b',
    messagingSenderId: '215908689362',
    projectId: 'flow-db99c',
    storageBucket: 'flow-db99c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1N16NkC3SEp3v8MqSh6XW2jr6w2J7jms',
    appId: '1:215908689362:ios:ade689820faa62411e540b',
    messagingSenderId: '215908689362',
    projectId: 'flow-db99c',
    storageBucket: 'flow-db99c.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
